//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Admin Page!.
        /// </summary>
        public static string AdminPageWelcomeMessage {
            get {
                return ResourceManager.GetString("AdminPageWelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string AlertDialogAcceptButtonText {
            get {
                return ResourceManager.GetString("AlertDialogAcceptButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not Valid.
        /// </summary>
        public static string AlertDialogEmailValidationMessage {
            get {
                return ResourceManager.GetString("AlertDialogEmailValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string AlertDialogPasswordMessage {
            get {
                return ResourceManager.GetString("AlertDialogPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert!.
        /// </summary>
        public static string AlertDialogTitle {
            get {
                return ResourceManager.GetString("AlertDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName is required.
        /// </summary>
        public static string AlertDialogUserNameMessage {
            get {
                return ResourceManager.GetString("AlertDialogUserNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Request.
        /// </summary>
        public static string BadRequestDialogTitle {
            get {
                return ResourceManager.GetString("BadRequestDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t Login.
        /// </summary>
        public static string BadRequestLoginMessage {
            get {
                return ResourceManager.GetString("BadRequestLoginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Custom Dialog.
        /// </summary>
        public static string BtnTextShowCustomDialog {
            get {
                return ResourceManager.GetString("BtnTextShowCustomDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Error Dialog.
        /// </summary>
        public static string BtnTextShowErrorDialog {
            get {
                return ResourceManager.GetString("BtnTextShowErrorDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Device Orientation.
        /// </summary>
        public static string ButtonGetDeviceOrientation {
            get {
                return ResourceManager.GetString("ButtonGetDeviceOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Photo.
        /// </summary>
        public static string ButtonPickPhoto {
            get {
                return ResourceManager.GetString("ButtonPickPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speak.
        /// </summary>
        public static string ButtonSpeak {
            get {
                return ResourceManager.GetString("ButtonSpeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any internet connection..
        /// </summary>
        public static string ConnectionInternetNotAvailable {
            get {
                return ResourceManager.GetString("ConnectionInternetNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your internet connection..
        /// </summary>
        public static string ConnectionPleaseCheckInternet {
            get {
                return ResourceManager.GetString("ConnectionPleaseCheckInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a custom user dialog.
        /// </summary>
        public static string CustomAlertDialogMessage {
            get {
                return ResourceManager.GetString("CustomAlertDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Dialog.
        /// </summary>
        public static string CustomDialogCloseButtonText {
            get {
                return ResourceManager.GetString("CustomDialogCloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email.
        /// </summary>
        public static string EmailPlaceholder {
            get {
                return ResourceManager.GetString("EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or Password is wrong.
        /// </summary>
        public static string ErrorDialogLoginAuthMessage {
            get {
                return ResourceManager.GetString("ErrorDialogLoginAuthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string ErrorDialogTitle {
            get {
                return ResourceManager.GetString("ErrorDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Orientation.
        /// </summary>
        public static string LabelDeviceOrientation {
            get {
                return ResourceManager.GetString("LabelDeviceOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Picker.
        /// </summary>
        public static string LabelPhotoPicker {
            get {
                return ResourceManager.GetString("LabelPhotoPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Details.
        /// </summary>
        public static string LogAlertDialogTitle {
            get {
                return ResourceManager.GetString("LogAlertDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Page.
        /// </summary>
        public static string MasterPageLabel {
            get {
                return ResourceManager.GetString("MasterPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string MenuNameAboutUs {
            get {
                return ResourceManager.GetString("MenuNameAboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string MenuNameAdmin {
            get {
                return ResourceManager.GetString("MenuNameAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string MenuNameContactUs {
            get {
                return ResourceManager.GetString("MenuNameContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependency Services.
        /// </summary>
        public static string MenuNameDependencyServices {
            get {
                return ResourceManager.GetString("MenuNameDependencyServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string MenuNameHome {
            get {
                return ResourceManager.GetString("MenuNameHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string MenuNameLogOut {
            get {
                return ResourceManager.GetString("MenuNameLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top News Categories.
        /// </summary>
        public static string MenuNameNewsCategoryList {
            get {
                return ResourceManager.GetString("MenuNameNewsCategoryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest News.
        /// </summary>
        public static string MenuNameNewsList {
            get {
                return ResourceManager.GetString("MenuNameNewsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your password.
        /// </summary>
        public static string PasswordPlaceholder {
            get {
                return ResourceManager.GetString("PasswordPlaceholder", resourceCulture);
            }
        }
    }
}
